obj-y := dsp/ ipc/ soc/ asoc/ asoc/codecs/ asoc/codecs/lpass-cdc/ asoc/codecs/wsa883x/ asoc/codecs/wcd938x/ asoc/codecs/wcd937x/

ifeq ($(ASUS_AI2202_AUDIO), y)
$(warning build audio factory function in Kbuild for AI2202...)
KBUILD_CPPFLAGS += -DASUS_AI2202_PROJECT=1
endif
